codestates-seb/seb44_main_003

client/src/components/Carousel.tsx
client/src/pages/Root.tsx
client/src/style/style.ts

fix: css fix3

---

client/src/style/style.ts

fix: fix alignment style

---

client/src/pages/Root.tsx
client/src/style/style.ts

데스크톱뷰에서는 16px, 모바일뷰에서는 13px의 기본 폰트 크기를 설정했습니다.

feat: set global font size for mobile view

---

server/src/main/java/com/ott/server/exception/ExceptionCode.java
server/src/main/java/com/ott/server/media/controller/MediaController.java
server/src/main/java/com/ott/server/media/dto/CreateOrUpdateMediaDto.java
server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/dto/MediaResponseDto.java
server/src/main/java/com/ott/server/media/entity/Media.java
server/src/main/java/com/ott/server/media/mapper/MediaMapper.java
server/src/main/java/com/ott/server/media/repository/MediaRepository.java
server/src/main/java/com/ott/server/media/service/MediaService.java

feat: add media function

---

client/src/components/carousel/Carousel.tsx

fix: 오타수정, 배포테스트

---

client/src/components/carousel/Carousel.tsx

fix: 디버깅, 배포테스트

---

server/src/main/java/com/ott/server/review/controller/ReviewController.java
server/src/main/java/com/ott/server/review/dto/MemberDetailDto.java
server/src/main/java/com/ott/server/review/dto/ReviewCreateDto.java
server/src/main/java/com/ott/server/review/dto/ReviewDetailDto.java
server/src/main/java/com/ott/server/review/dto/ReviewDto.java
server/src/main/java/com/ott/server/review/dto/ReviewListDto.java
server/src/main/java/com/ott/server/review/dto/ReviewUpdateDto.java
server/src/main/java/com/ott/server/review/entity/Review.java
server/src/main/java/com/ott/server/review/repository/ReviewRepository.java
server/src/main/java/com/ott/server/review/service/ReviewService.java

feat: review 추가

---

server/src/main/java/com/ott/server/bookmark/controller/BookmarkController.java
server/src/main/java/com/ott/server/bookmark/dto/BookmarkDto.java
server/src/main/java/com/ott/server/bookmark/entity/Bookmark.java
server/src/main/java/com/ott/server/bookmark/mapper/BookmarkMapper.java
server/src/main/java/com/ott/server/bookmark/repository/BookmarkRepository.java
server/src/main/java/com/ott/server/bookmark/service/BookmarkService.java
server/src/main/java/com/ott/server/exception/ExceptionCode.java
server/src/main/java/com/ott/server/interest/dto/InterestDto.java
server/src/main/java/com/ott/server/interest/repository/InterestRepository.java
server/src/main/java/com/ott/server/member/controller/MemberController.java
server/src/main/java/com/ott/server/member/dto/MemberDto.java
server/src/main/java/com/ott/server/member/entity/Member.java
server/src/main/java/com/ott/server/memberott/dto/MemberOttDto.java
server/src/main/java/com/ott/server/memberott/repository/MemberOttRepository.java

feat: 북마크 기능 구현

---

server/src/main/java/com/ott/server/recommendation/controller/RecommendationController.java
server/src/main/java/com/ott/server/recommendation/dto/RecommendationDto.java
server/src/main/java/com/ott/server/recommendation/entity/Recommendation.java
server/src/main/java/com/ott/server/recommendation/mapper/RecommendationMapper.java
server/src/main/java/com/ott/server/recommendation/repository/RecommendationRepository.java
server/src/main/java/com/ott/server/recommendation/service/RecommendationService.java

feat: recommendation

---

client/package-lock.json
client/src/api/api.ts
client/src/components/Banner.tsx
client/src/components/Item.tsx
client/src/components/Silder/Silder.tsx
client/src/pages/TV.tsx
client/src/types/types.ts

-  Slider의 ltem 요소 컴포넌트화
- 에러 수정
- `src/components/Item.tsx(14,10): error TS6133: 'swiperRef' is declared but its value is never read.`

feat/item: Slider의 ltem 요소 컴포넌트화, 일부 에러 수정

---

client/src/components/header/Header.tsx

헤더에 absolute값을 줘서 메인 요소가 아래로 비치게 만들었습니다

feat: fix header to transparent background

---

client/src/components/silde/Silde.tsx
client/src/pages/TV.tsx

fix: silder 컴포넌트명 silde로 변경

---

client/src/App.tsx

{
path: 'content/:id',
element: <Content />,
},
{
path: 'search/:userInput?/:ott?/:genre?',
element: <Search />,
},

fix: 동적 파라미터 추가

---

server/src/main/java/com/ott/server/media/controller/MediaController.java
server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/mapper/MediaMapper.java
server/src/main/java/com/ott/server/media/service/MediaService.java

testing method to return all media

feat: all media return testing method

---

server/src/main/resources/application-server.yml

fix: yml OAuth part update

---

client/src/api/api.ts
client/src/components/silde/SildeMovie.tsx
client/src/components/ui/ItemCard.tsx
client/src/pages/Movie.tsx

- 리액트 쿼리로 리팩토링
* 미디어 서버 연결 테스트 진행
<br>
- 기존의 슬라이더 형식으로 보여지도록 해야 함

feat/apitest: 미디어 서버 연결 테스트

---

client/src/api/api.ts
client/src/components/authentication/LoginForm.tsx
client/src/pages/Main.tsx

fix: fix login errors

---

client/src/api/api.ts
client/src/components/ListBtns.tsx
client/src/components/silde/InfinityScroll.tsx
client/src/components/ui/GenreBtn.tsx
client/src/pages/Search.tsx

fix: 타입 에러수정, feat: genre 버튼

---

client/src/components/header/Dropdown.tsx
client/src/components/header/UserProfile.tsx
client/src/pages/Main.tsx

feat: add dropdown menu to header

---

client/src/api/api.ts
client/src/components/ListBtns.tsx
client/src/components/ui/GenreBtn.tsx
client/src/components/ui/OttBtn.tsx
client/src/pages/List.tsx
client/src/pages/Movie.tsx
client/src/pages/TV.tsx

훅을 따로 만들진 않았지만 약간의 깔끔함을 위한 코드 수정
Search 페이지
1. [ ] css, 반응형
2. [ ] db가 약간 다르기 때문에 수정필요
3. [ ] 로딩, err 처리 필요
List 페이지
1. [ ] css, 반응형
2. [x] axios 요청
3. [x] ott 버튼
4. [x] genre 버튼
InfinityScroll 컴포넌트
1. [ ] css, 반응형
OttBtn 컴포넌트
1. [x] 위지 임의 지정 해뒀습니다
2. [x] tv, movie에선 밝은상태, List페이지 에서는 default로 dark에서 활성화시 light
Genre 컴포넌트
1. [x] 위지 OttBtn 옆에 지정 해뒀습니다
2. [ ] ui, ux

feat: 장르선택, axios요청

---

client/src/pages/Root.tsx
client/src/styles/style.ts

tv, 영화 페이지가 아닌 곳에 padding-top을 추가해 줬습니다.

feat: add padding-top at root style

---

client/src/components/silde/SildeMovie.tsx
client/src/components/silde/SildeTV.tsx
client/src/components/ui/ItemCard.tsx

:lipstick: Fix: 슬라이더 오류 해결

---

server/src/main/java/com/ott/server/media/controller/MediaController.java
server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/entity/Media.java
server/src/main/java/com/ott/server/media/repository/MediaRepository.java
server/src/main/java/com/ott/server/media/service/MediaService.java
server/src/main/java/com/ott/server/review/controller/ReviewController.java
server/src/main/java/com/ott/server/review/dto/ReviewDetailDto.java
server/src/main/java/com/ott/server/review/repository/ReviewRepository.java
server/src/main/java/com/ott/server/review/service/ReviewService.java

fix: media default value fix, add review method

---

server/src/main/java/com/ott/server/auth/service/OAuth2MemberService.java
server/src/main/java/com/ott/server/member/entity/Member.java

fix: oauth 수정

---

server/src/main/java/com/ott/server/media/controller/MediaController.java
server/src/main/java/com/ott/server/media/repository/MediaRepository.java
server/src/main/java/com/ott/server/media/service/MediaService.java

fix: media

---

server/src/main/java/com/ott/server/media/mapper/MediaMapper.java

fix: MediaMapper fix

---

client/src/api/api.ts
client/src/components/contents/Bookmark.tsx
client/src/components/contents/ContentDetail.tsx
client/src/pages/Content.tsx
client/src/types/types.ts

글 디테일->  크리에이터: '감독', cast: '출연진', title: '숫자(해당id)', titlePoster 없는것만: '귀멸의 칼날(제목title)' 
으로 응답받고있음 (백에 전달했음)
북마크 토글형식.
글 디테일에서 로그인하러가면 /undefined 로 라우팅이 되고있음.

feat: 북마크 추가, 글 디테일 추가

---

client/src/components/contents/Bookmark.tsx
client/src/components/contents/ContentDetail.tsx
client/src/components/ui/Tag.tsx

taleTime: 5 * 60 * 1000 에서 Infinity 로 변경
태그 스타일 피그마에 정의한대로 수정

fix: 태그 스타일 변경, staletime 변경

---

client/src/api/api.ts
client/src/components/contents/Bookmark.tsx
client/src/components/contents/ContentDetail.tsx
client/src/components/contents/Recommend.tsx
client/src/components/ui/GenreBtn.tsx
client/src/components/ui/Tag.tsx
client/src/styles/style.ts

Recommend 컴포넌트 추가
Bookmark, Recommend 공통 css 사용
Tag 컴포넌트 간격 조절
GenreBtn z-index 조절

feat: 추천, css수정

---

client/src/api/api.ts
client/src/components/authentication/SignupForm.tsx
client/src/components/comments/CommentContent.tsx
client/src/components/comments/CommentForm.tsx
client/src/components/comments/CommentSection.tsx
client/src/components/comments/Comments.tsx
client/src/constant/constantValue.ts
client/src/types/types.ts
client/src/utils/datetime.ts

1. [x] ui 구현
2. [x] 로그인 상태에 따른 조건부 렌더링
3. [x] 전송 누르면 post 요청
4. [x] 페이지네이션
5. [x] 댓글 수정 삭제 기능

Feat/comments 상세조회 후기 구현

---

client/src/components/comments/CommentContent.tsx
client/src/components/comments/Comments.tsx

디테일 페이지 이동했을 때 후기가 새로 불러와지지 않는 현상을 해결했습니다.

Feat/comments 후기 작성 버그 해결

---

server/src/main/java/com/ott/server/crawling/CrawlingController.java
server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/entity/Media.java
server/src/main/java/com/ott/server/media/service/MediaService.java
server/src/main/java/com/ott/server/mediaott/entity/MediaOtt.java

OTT 별 상세 주소 추가에 따른 media Response 변경.
crawling 수정

fix: mediaTable and crawling

---

client/src/components/header/Header.tsx

- 메인 캐러셀이 화면에 보이는 구간까지는 헤더를 숨기지 않도록 조절했습니다.

fix: 헤더 숨기는 스크롤 위치 수정

---

.idea/gradle.xml
server/src/main/java/com/ott/server/media/controller/MediaController.java
server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/service/MediaService.java
server/src/main/java/com/ott/server/recommendation/repository/RecommendationRepository.java

feat: 추천순으로 미디어 정렬 기능 추가

---

server/src/main/java/com/ott/server/media/dto/MediaDto.java
server/src/main/java/com/ott/server/media/entity/Media.java
server/src/main/java/com/ott/server/report/entity/Report.java
server/src/main/java/com/ott/server/review/controller/ReviewController.java
server/src/main/java/com/ott/server/review/repository/ReviewRepository.java
server/src/main/java/com/ott/server/review/service/ReviewService.java

멤버 리뷰 조회 기능 추가
Media create 오류 수정

feat: 멤버 리뷰 조회 기능 추가

---

server/src/main/java/com/ott/server/report/controller/ReportController.java
server/src/main/java/com/ott/server/report/mapper/ReportMapper.java

fix: report response

---

client/src/api/api.ts
client/src/components/admin/AdminMediaForm.tsx
client/src/components/contents/ContentDetail.tsx
client/src/components/contents/ReportBtn.tsx
client/src/components/modal/questions/QuestionResult.tsx
client/src/components/ui/modal/Modal.tsx
client/src/components/ui/modal/ReportModal.tsx
client/src/hooks/useModal.ts
client/src/recoil/atoms/Atoms.ts
client/src/types/types.ts

전역 상태 추가 isOpen === boolean, content ===JSX.Element | string 
```export const modalState = atom<ModalType>({
key: 'modalState',
default: {
isOpen: false,
content: '',
},
});
```
useModal 훅은 ```return { modalDataState, closeModal, openModal }``` 을 리턴
모달을 켜줄 버튼 컴포넌트에
``` 
const { openModal } = useModal();
const modalData = {
content: <ReportModal />, // 컴포넌트를 컨텐트에 담아줌
};
<>
<S_Button onClick={() => openModal(modalData)}/> // 이렇게 사용하면 모달에 담깁니다
<Modal />
</>
```
```const { closeModal } = useModal();``` 담아준 컴포넌트 내부에서 닫기함수를 불러서 사용하면됩니다.
Modal에는 열렸을때 스크롤방지, 외부클릭시 닫기를 적용해뒀습니다
모달은 UI 폴더 => Modal 폴더를 새로 만들어뒀습니다

Feat/admin 오류 제보 추가, usemodal 훅 추가

---

client/src/components/contents/ReportBtn.tsx
client/src/pages/Root.tsx

Modal은 전역상태를 받기때문에 컴포넌트를 따로 호출하지 않아도 됩니다.

fix: 모달 전역으로 변경

---

client/src/components/slide/InfinityScroll.tsx
client/src/components/ui/ListBtns.tsx
client/src/components/ui/exceptions/infinityScroll.tsx
client/src/pages/Auth.tsx
client/src/types/types.ts

무한스크롤 css 수정(노가다), 장르 css 동적으로 수정
로그인, 회원가입 배경 스크롤바 제거

Fix/contents 무한스크롤 css 수정, 장르 css수정

---

client/src/api/api.ts
client/src/components/admin/AdminMediaForm.tsx
client/src/components/admin/AdminReport.tsx
client/src/components/admin/DeleteMediaBtn.tsx
client/src/components/contents/ReportBtn.tsx
client/src/components/slide/InfinityScroll.tsx
client/src/components/ui/exceptions/infinityScroll.tsx
client/src/components/ui/modal/ReportDetail.tsx
client/src/pages/Admin.tsx
client/src/pages/Search.tsx
client/src/types/types.ts

무한스크롤 타입 에러 수정, 동적 css로 api 안불러와지는 현상 수정
관리자 리포트 조회, 이동, 삭제 구현

Fix/contents 타입 에러 진짜 수정, 관리자 리포트 조회, 삭제

---

client/src/components/modal/Recommend.tsx
client/src/components/modal/questions/FirstQuestion.tsx
client/src/components/modal/questions/QuestionResult.tsx
client/src/components/modal/questions/SecondQuestion.tsx
client/src/components/modal/questions/ThirdQuestion.tsx
client/src/recoil/atoms/Atoms.ts
client/src/types/types.ts

헤더, 메인 배너 추천해조잉 버튼 클릭 시 모달이 열리지 않는 현상을 해결했습니다.
useModal 훅을 사용해 모달을 띄우도록 만들고 recommendModalState에 의존하지 않도록 리팩터했습니다.

Feat/header 추천해조잉 모달 열리지 않는 현상 해결

---

server/src/main/java/com/ott/server/media/entity/Media.java
server/src/main/java/com/ott/server/search/service/SearchService.java

fix: autocomplete bug

---

server/src/main/java/com/ott/server/search/controller/SearchController.java
server/src/main/java/com/ott/server/search/dto/MultiResponseDtoSearch.java

fix: totalResults added

---

server/src/main/java/com/ott/server/media/service/MediaService.java
server/src/main/java/com/ott/server/member/dto/MemberDto.java

fix: media patch

---

client/.gitignore
client/src/api/api.ts
client/src/components/member/MemberInfo/Information.tsx
client/src/components/member/MemberLikesModal.tsx
client/src/components/member/memberContents/ReviewList.tsx
client/src/components/member/profileModal/ProfileModal.tsx
client/src/constant/constantValue.ts
client/src/styles/style.ts
client/src/types/types.ts
client/src/utils/convertResponse.ts

멤버페이지에 멤버 선호도(카테고리, ott, 장르) 변경 기능을 추가했습니다.

Feat/member 멤버 선호도 변경 기능 추가

---

client/src/components/comments/CommentContent.tsx
client/src/components/member/memberContents/ReviewList.tsx
client/src/types/types.ts

멤버페이지에서 후기 조회 기능(만) 구현했습니다.
멤버페이지의 '작성한 후기' 탭 클릭

feat: 멤버 후기 조회 기능 구현

---

client/src/components/comments/CommentContent.tsx
client/src/components/comments/CommentForm.tsx
client/src/components/comments/CommentSection.tsx
client/src/components/comments/Comments.tsx

후기 컴포넌트의 스타일링과 로직 전반을 수정했습니다. 특히 후기 컴포넌트 재사용성 향상을 위해 쿼리 요청을 컴포넌트 밖으로 분리하고 페이지네이션 로직 오류를 해결했습니다.
후기를 써보세요.. 아주 많이... 그리고 길게..

Feat/comments 후기 컴포넌트 기능 수정

---

client/src/components/comments/Comments.tsx

fix: svg 아이콘 크기 수정, 커서 포인터

---

server/src/main/java/com/ott/server/media/service/MediaService.java

fix: media patch update

---

client/src/components/contents/RecommendContent.tsx
client/src/components/slide/GenreSlide.tsx
client/src/components/slide/mainslider/MainSlider.tsx
client/src/components/ui/RecommendBtn.tsx
client/src/components/ui/questions/QuestionData.tsx
client/src/components/ui/questions/QuestionResult.tsx
client/src/components/ui/questions/Recommend.tsx
client/src/components/ui/questions/ThirdQuestion.tsx
client/src/pages/Movie.tsx
client/src/pages/TV.tsx

✏️ Fix: 불필요한 주석 제거, 추천해조잉 결과 요청 url 수정

---

client/src/components/ui/questions/FirstQuestion.tsx
client/src/components/ui/questions/QuestionResult.tsx
client/src/components/ui/questions/SecondQuestion.tsx
client/src/components/ui/questions/ThirdQuestion.tsx

- 커서 포인터 추가
- brightness 효과 추가

:lipstick: Fix: 추천해조잉 아이콘 hover시 ui 개선

---

client/src/components/contents/ContentDetail.tsx
client/src/components/ui/Tag.tsx

fix: 디테일 css 수정

---

client/src/components/header/Header.tsx
client/src/components/header/Navigation.tsx
client/src/components/ui/MobileGNB.tsx
client/src/pages/Root.tsx

뷰포트 600px 이하에서 생기는 모바일 gnb를 만들었습니다.

Feat/header 모바일 gnb ui 완성

---

client/src/components/banner/MainBanner.tsx
client/src/components/header/Navigation.tsx
client/src/components/ui/MobileGNB.tsx
client/src/components/ui/MoveBtn.tsx
client/src/components/ui/questions/FirstQuestion.tsx
client/src/components/ui/questions/QuestionData.tsx
client/src/components/ui/questions/QuestionResult.tsx
client/src/components/ui/questions/RecommendModal.tsx
client/src/components/ui/questions/SecondQuestion.tsx
client/src/components/ui/questions/ThirdQuestion.tsx

:package: Fix: 서버에 저장된 이미지로 변경, 파일명 수정

---

client/src/components/slide/GenreSlide.tsx
client/src/components/ui/ItemCard.tsx

:iphone: Fix: TV, Movie 페이지 슬라이더 반응형 ui 구현

---

client/src/App.css
client/src/api/api.ts
client/src/components/header/Header.tsx
client/src/components/header/SearchBar.tsx
client/src/components/ui/MobileGNB.tsx
client/src/constant/constantValue.ts

데스크탑뷰의 서치바를 통한 검색어 자동완성 기능을 구현했습니다

Feat/header 검색어 자동완성 기능 구현

---

client/src/components/slide/GenreSlide.tsx
client/src/components/slide/mainslider/MainSlider.tsx
client/src/components/slide/mainslider/MainSliderSection.tsx

:iphone: Fix: 메인 슬라이더 반응형 ui 구현

---

client/src/api/api.ts
client/src/components/slide/GenreSlide.tsx

✏️ Fix: TV, Movie 요청 데이터 url 변경

---

client/src/components/ui/GenreBtn.tsx
client/src/components/ui/ListBtns.tsx
client/src/components/ui/modal/genre/MobileGenreModal.tsx

언마운트시에 애니메이션을 추가했습니다. 난 왜 굳이 이거 하려고 이렇게..

fix: 모바일 장르 언마운트 애니메이션

---

client/src/components/slide/GenreSlide.tsx
client/src/components/ui/ItemCard.tsx

:construction: Fix: 모바일일때 호버효과 없앰, 화살표 크기 키움

---

client/src/components/header/Header.tsx
client/src/components/header/MainLogo.tsx
client/src/components/header/Navigation.tsx
client/src/components/header/SearchBar.tsx
client/src/components/ui/MobileGNB.tsx

미디어쿼리 브레이크포인트의 통일성을 갖추면서 검색어 자동완성 기능을 잘 구현하기 위해 데스크탑뷰 헤더 수정했습니다.
모바일뷰에서 검색 및 검색어 자동완성 기능을 구현했습니다.

Feat/header 데스크탑뷰 헤더 수정, 모바일뷰 검색 기능 구현

---

client/src/components/contents/ContentDetail.tsx
client/src/components/slide/InfinityScroll.tsx
client/src/components/ui/GenreBtn.tsx
client/src/components/ui/Tag.tsx
client/src/components/ui/exceptions/InfinityScrollLoading.tsx
client/src/pages/Auth.tsx
client/src/pages/List.tsx

이전 pr 에서 수정한 style로 부서진 auth 원상복구
무한스크롤 페이지, 디테일 페이지 미디어쿼리 수정

Fix/infinityscroll 미디어쿼리 수정

---

client/src/components/authentication/Authentication.tsx
client/src/components/comments/Comments.tsx
client/src/components/header/Navigation.tsx
client/src/components/member/MemberInfo/Information.tsx
client/src/components/member/MemberInfo/MemberInfo.tsx
client/src/components/member/memberContents/ContentsList.tsx
client/src/components/member/memberContents/MemberContents.tsx
client/src/pages/Auth.tsx
client/src/pages/Member.tsx

유저페이지 양측 마진 손봤습니다
로그인/회원가입 폼 모바일뷰 너비 수정했습니다.
css 그만 하고 싶습니다.

fix: css 이것저것..

---

client/src/api/api.ts
client/src/components/authentication/LoginForm.tsx
client/src/components/header/UserProfile.tsx

리프레시 토큰 처리가 제대로 이뤄지지 않아 일단은 30분이 지나면 로그아웃 되게 처리했습니다.

fix: 리프레시 토큰 작동 오류로 일단 로그아웃 로직 되돌림

---

client/src/components/slide/GenreSlide.tsx
client/src/pages/Movie.tsx
client/src/pages/TV.tsx

- 유일한 "key" 값을 부여함
- slidesPerView와, slidesPerGroup 개수를 일치시킴

🥅 Fix: tv, moive 페이지 key 오류, 슬라이더 밀림 현상 해결 🥳

---

server/src/main/resources/application-server.yml

feat: application.yml log file added

---

client/src/components/authentication/AdditionalInfo.tsx
client/src/components/comments/CommentContent.tsx
client/src/components/comments/CommentForm.tsx
client/src/components/comments/CommentSection.tsx
client/src/components/comments/Comments.tsx
client/src/components/member/MemberInfo/Information.tsx
client/src/components/member/MemberInfo/MemberInfo.tsx
client/src/index.css
client/src/pages/Auth.tsx
client/src/styles/global-styles.ts

폰트 404 오류 해결을 위해 index.css로 폰트 설정을 옮겼습니다.
로그인, 회원가입 페이지 링크에 호버 스타일을 적용했습니다.
마이페이지 모바일뷰에서 버튼들이 오른쪽으로 밀리는 현상을 해결했습니다.

Feat/member css 설정 변경

---

client/src/api/api.ts
client/src/components/authentication/LoginForm.tsx
client/src/components/authentication/SignupForm.tsx
client/src/components/header/UserProfile.tsx
client/src/components/ui/TopButton.tsx
client/src/constant/constantValue.ts
client/src/hooks/useTokens.ts
client/src/pages/Main.tsx
client/src/pages/Root.tsx

리프레시 토큰 처리를 구현했습니다. 액세스토큰은 30분, 리프레시 토큰은 24시간 유효합니다.

Feat/member 리프레시 토큰 처리 구현

---

client/package-lock.json
client/package.json
client/src/components/contents/Bookmark.tsx
client/src/components/contents/Recommend.tsx
client/src/components/contents/ReportBtn.tsx
client/src/components/slide/GenreSlide.tsx
client/src/components/ui/GenreBtn.tsx
client/src/components/ui/Toast.tsx
client/src/components/ui/modal/report/ReportModal.tsx
client/src/pages/Root.tsx
client/src/utils/notify.ts

react-hot-toast 설치
ui -> Toast 컴포넌트 (공통 스타일 변경은 해당 컴포넌트에서)
utils -> notify.ts
```
export const notifyError = (notify: string) => toast.error(`${notify}`);
export const notifySuccess = (notify: string) => toast.success(`${notify}`);
export const notifyWithIcon = (notify: string, icon: string) =>
toast(`${notify}`, {
icon: `${icon}`,
});
```
notifyError =  ❌ 아이콘과함께 메세지출력
notifySuccess = ✅ 아이콘과함께 메세지출력
notifyWithIcon = 1번째 메세지, 2번째 이모지 넣어서 사용
북마크 컴포넌트 예제)
```import { notifyError, notifyWithIcon } from '../../utils/notify';```
```onClick={() => notifyError('로그인 후 이용 가능합니다')}``` alert 대신 notifyError 함수 사용
```
if (!data) {
notifyWithIcon('찜 완료!', '❤️');
} else {
notifyWithIcon('찜 취소..', '🤍');
}
```
북마크 상태에 따른 메세지 출력

feat: 토스터 인스톨, 추가

---

client/index.html
client/src/components/ui/questions/ThirdQuestion.tsx

- SNS에서 링크를 공유할 때 뜨는 이미지와 제목 및 설명 등을 오픈그래프를 통해 설정할 수 있다.

Feat/opengraph 오픈그래프 적용

---

client/index.html

:pencil2: Fix: 오타 수정

---

client/src/components/authentication/SignupForm.tsx
client/src/components/member/MemberInfo/Information.tsx
client/src/components/member/MemberLikesModal.tsx
client/src/components/ui/questions/QuestionResult.tsx

fix: notify 추가

---

client/index.html

feat: GA 세팅

---

client/src/components/header/SearchBar.tsx

fix: 검색창 모달 높이 변경

---

client/src/components/contents/ContentDetail.tsx
client/src/components/contents/RecommendContent.tsx
client/src/components/header/UserProfile.tsx
client/src/components/member/MemberInfo/MemberProfile.tsx
client/src/components/slide/GenreSlide.tsx
client/src/components/ui/questions/QuestionResult.tsx

feat: 에러 처리 보강

---

client/src/components/banner/MainBanner.tsx

feat: 메인 배너 애니메이션 추가

---

server/src/main/java/com/ott/server/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/java/com/ott/server/config/SecurityConfiguration.java

fix: 오어스 레디스 문제

---

server/src/main/java/com/ott/server/auth/handler/OAuth2AuthenticationSuccessHandler.java
server/src/main/java/com/ott/server/config/SecurityConfiguration.java

fix: 레디스 수정

---

client/src/components/comments/CommentForm.tsx
client/src/components/header/LoginSignup.tsx
client/src/components/header/MainLogo.tsx
client/src/components/header/Navigation.tsx
client/src/components/header/SearchBar.tsx

피드백 받은 것 중 간단하게 처리 가능한 css적 부분에 대해서 처리했습니다.

feat: 자동검색 깜빡임 제거
